# Generated by Django 5.1.1 on 2026-07-03 10:45

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Формат: ГГГГ-ММ-ДД', verbose_name='Дата операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))], verbose_name='Сумма, руб.')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='references.category', verbose_name='Категория')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='references.operationtype', verbose_name='Тип')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='references.status', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='references.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Операция ДДС',
                'verbose_name_plural': 'Операции ДДС',
                'ordering': ['-date'],
            },
        ),
    ]
